baseURL = "https://braindump.badykov.com/"
languageCode = "en-us"
title = "Airat's Braindump"
theme = "cortex"


[params]
email = "ayratin555@gmail.com"
footer = "Icon by Freepik. Built with ♥ with Org-mode and Hugo."