baseURL = "https://braindump.badykov.com/"
languageCode = "en-us"
title = "Airat's Braindump"
theme = "cortex-dark"
pygmentsStyle = "dracula"

[params]
email = "ayratin555@gmail.com"
footer = "Icon by Freepik. Built with ♥ with Org-mode and Hugo."
entrypoint = "/about"