:PROPERTIES:
:ID:       51C4735C-BCF0-4C71-A917-700D8AC71253
:END:
#+title: Emacs
#+filetags: :emacs:productivity:braindump:

Emacs is an (esoteric) text editor. Its key feature is extensibility. Emacs provides Emacs Lisp programming language which is used to write extensions.

Great Emacs packages:

- [[https://magit.vc/][Magit]] - a git interface
- [[id:BA8CAFC9-6132-4761-BAFB-EF05C5C3306A][Org-Mode]] is a document editing, formatting, and organizing mode
- [[id:695E8B9A-73D7-4D3F-89F2-5D11D1BA2A61][Org-Roam]] is a personal knowledge management tool

You can check out [[https://www.badykov.com/emacs/2018/07/31/why-emacs-is-a-great-editor/][my blog post]] I wrote a long time ago where I'm trying to sell Emacs.

My emacs config can be found in [[https://github.com/ayrat555/dot-emacs][the github repo]]

The only problem I have with Emacs is it drains my [[id:F9AF4505-79F3-4342-B0B2-14979760CD0F][free time]] :)

I wrote several [[id:13C6A138-2ECE-4E84-9340-1EABF64ECD42][emacs packages]]

* [[id:9E08E9F9-8A29-4F21-B399-CD308ED43202][Emacs Tweaks]]

* My emacs configuration backlog:

- Start emacs server on macos boot
  Creating plist and additing `Library/LaunchAgents` starts two daemons, using just `em ./` starts one daemon

- Set up org-capture shortcuts from anywhere
   using org-protocol

- Figure out / clean types of notes

   I think content to consume  should only have main type notes, without notes for separate movies etc

- Emacs creates garbage files in home directory

- Try org-super-agenda
   https://github.com/alphapapa/org-super-agenda

- Check https://github.com/progfolio/doct

- Check https://github.com/manateelazycat/snails

- Fix org-journal agenda for new files

- Make long lines separated in the compilation mode separated

* Backlog for this note

- Add emacs packages that I use
